### PR TITLE
add freemanjiang.com

### PR DESCRIPTION
**Pull request by freeman-jiang**
Website Link: https://www.freemanjiang.com/

### CODE REVIEW

**Review by JusGu — APPROVED** [review]
nice! (lets move your new website to the bottom so the original order is maintained)

**Review by Arcslogger — COMMENTED** [review]
@freeman-jiang we added a few new websites so make sure u pull `main` before updating 🙏

**Comment by freeman-jiang** [comment]
@Arcslogger @JusGu updated!

**Comment by Arcslogger** [comment]
🫡

**Review by Arcslogger — APPROVED** [review]
🫡

**Pull request merged**
